- name: Playbook to update repositories and install net-tools
  hosts: all
  become: true
  tasks:
    - name: Update apt repository
      apt:
        update_cache: yes
    - name: Update apt install net-tools
      apt: 
        name: net-tools
        update_cache: yes
        state: latest

#https://github.com/angryip/ipscan/releases/download/3.7.4/ipscan_3.7.4_amd64.deb