- hosts: all
  become: yes
  remote_user: ansible
  tasks:
  - name: Rename hosts
    tags: rename
    hostname:
        name: "{{ hostname.name }}"

  - name: Copy readme file to hostname
    tags: copy
    copy:
      src: readme.txt
      dest: /home/ubuntu
      owner: ubuntu
      group: ubuntu
      mode:  0644


